### ISSUE TITLE
Feedback for /mapbox-gl-js/example/add-image-animated/

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#100]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/add-image-animated/](https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/)
* Section: null
* Date received: 2019-10-01T15:54:01.080Z
* Was this page helpful?: 😕

Feedback:
> Some comments to explain what exactly is going on?  When is onAdd() called?  When is render() called?

This example is quite confusing. It's not clear that the image being passed to `addImage` is being drawn. And it's not clear why it's being done that way.

**Comment by asheemmamoowala** [comment]
The goal of this example is to document how to custom draw an icon. The `render` method is called for each frame, and since it calls `map.triggerRepaint`, it is repainting the map continuously, resulting in the smooth animation of the dot.

cc @ansis
