### ISSUE TITLE
[Feedback] add some next steps to /mapbox-gl-js/overview/

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#101]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/overview/](https://docs.mapbox.com/mapbox-gl-js/overview/)
* Section: null
* Date received: 2019-10-02T17:22:59.499Z
* Was this page helpful?: 😕

Feedback:
> It would be great if there was a tutorial as part of the getting started on how to add data to the map. The getting started gets me to the point where I have a map on screen, but I want to know how to add pins to it. I can search in the examples but then I have an overwhelming number of different tutorials to sift through (most of which are far to advanced) to find what I want.

**Comment by danswick** [comment]
Noting that we got another request for this type of thing.

**Comment by katydecorah** [comment]
I see a couple options for this one:

1. We close this issue since the sidebar now has a "Tutorials" link and we haven't received feedback since the info arch update.

2. At the bottom, of https://docs.mapbox.com/mapbox-gl-js/api/#quickstart we add a list of 3 Help tutorials:

```md
Try a tutorial for step-by-step instructions:
- [Add custom markers in Mapbox GL JS](https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/)
- [Use Mapbox GL JS in a React app](https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/)
- [Build a store locator using Mapbox GL JS](https://docs.mapbox.com/help/tutorials/building-a-store-locator/)
````

@danswick I'm curious what you think!

**Comment by danswick** [comment]
Great point about info-arch and the tutorials link in the sidebar. Since we haven't gotten any additional feedback since info-arch, let's close this!
