### ISSUE TITLE
Feedback for /mapbox-gl-js/style-spec/ (Other filter)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#104]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/style-spec/](https://docs.mapbox.com/mapbox-gl-js/style-spec/)
* Section: Other filter
* Date received: 2019-10-09T18:11:18.674Z
* Was this page helpful?: 😕

Feedback:
> Need examples

**Comment by katydecorah** [comment]
Going to close here since this is now deprecated content
