### ISSUE TITLE
Feedback for /mapbox-gl-js/example/measure/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#106]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/measure/](https://docs.mapbox.com/mapbox-gl-js/example/measure/)
* Section: null
* Date received: 2019-10-08T13:45:43.401Z
* Was this page helpful?: 😕

Feedback:
> The turf.lineDistance() doesn't exist anymore. Its turf.length().

**Comment by danswick** [comment]
We got another request for this change. Let's see if we can get #173 merged!
