### ISSUE TITLE
Feedback for /mapbox-gl-js/api/ (on)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#107]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: https://docs.mapbox.com/mapbox-gl-js/api/#evented#on
* Section: on
* Date received: 2019-10-08T14:08:05.416Z
* Was this page helpful?: 😕

Feedback:
> A list or link to the event types would be nice :-)

**Comment by HeyStenson** [comment]
Second verse, same as the first:

> I would love to get a link here to which events are supported.

**Comment by katydecorah** [comment]
> /mapbox-gl-js/api/#map#on
> What are the types?

**Comment by katydecorah** [comment]
Closing in favor of #9
