### ISSUE TITLE
Feedback for /mapbox-gl-js/example/flyto-options/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#117]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/flyto-options/](https://docs.mapbox.com/mapbox-gl-js/example/flyto-options/)
* Section: null
* Date received: 2019-10-17T10:09:27.783Z
* Was this page helpful?: 😕

Feedback:
> The example is not working...there's no "slowly fly"

This is the second time this week we've gotten feedback on this example saying that it's not working.  (The other feedback, from 10/12, was simply: `It doesnt work`.) As far as I can tell, the example does exactly what it's supposed to - 

> // These options control the flight curve, making it move
> // slowly and zoom out almost completely before starting
> // to pan.  

However, the fact that we've gotten two separate pieces of feedback about this makes me think that user expectations may be different. What can we clarify in either the comments or the example header?

**Comment by pathmapper** [comment]
> the example does exactly what it's supposed to

If `prefers-reduced-motion` is set in browser preferences, there is currently no flyto animation.
Related issue: https://github.com/mapbox/mapbox-gl-js/issues/8743

**Comment by HeyStenson** [comment]
@pathmapper Thanks! I wasn't aware of mapbox/mapbox-gl-js#8743 - that context makes this feedback make a lot more sense.
