### ISSUE TITLE
Anchor links incorrectly generated in API documentation

### ISSUE THREAD

**Issue by adrianababakanian** [mapbox/mapbox-gl-js-docs#121]
## Steps to reproduce
The anchor links generated for each `a` tag in the [Mapbox GL JS API documentation](https://docs.mapbox.com/mapbox-gl-js/api/) are generated incorrectly. For example, consider the Map#addLayer link under the [CustomLayerInterface](https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface) section. The generated link is `https://docs.mapbox.com/mapbox-gl-js/api/#mapaddlayer`, when it should in fact be `https://docs.mapbox.com/mapbox-gl-js/api/#map#addlayer`.

## To fix
Change the generated URLs to `/#map#{methodname}` instead of `/#map{methodname}`.

**Comment by andrewharvey** [comment]
This is a duplicate issue of https://github.com/mapbox/mapbox-gl-js/issues/4568
