### ISSUE TITLE
getRTLTextPluginStatus and mercatorScale methods are in wrong category

### ISSUE THREAD

**Issue by life777** [mapbox/mapbox-gl-js-docs#131]
Hi,

getRTLTextPluginStatus method is in mapboxgl object, but it's listed in Events category in documentation. The same problem with mercatorScale.

![Screenshot from 2019-10-31 17-20-38](https://user-images.githubusercontent.com/891497/67987183-278a7e80-fc03-11e9-8a66-7c09dd001df8.png)

Thanks a lot for awesome docs.

**Comment by life777** [comment]
To be honest, I don't know where should be mercatorScale (I couldn't find it minified mapbox-gl,js file). Probably it's not a public API at all.

**Comment by asheemmamoowala** [comment]
@life777 In https://github.com/mapbox/mapbox-gl-js/pull/8856, `mercatorScale` was made private. 
`getRTLTextPluginStatus` just needs to be added to `docs/documentation.yml`.
