### ISSUE TITLE
addImage example results in an invalid arguments error

### ISSUE THREAD

**Issue by adrianababakanian** [mapbox/mapbox-gl-js-docs#135]
The provided [example](https://docs.mapbox.com/mapbox-gl-js/api/#map#addimage) in the API documentation for `Map#addImage` results in the following error (when the [add an icon to the map](https://docs.mapbox.com/mapbox-gl-js/example/add-image/) example is modified to use a local image instead of one from an external URL):
```
Error: Invalid arguments to map.addImage(). The second argument must be an `HTMLImageElement`, `ImageData`, or object with `width`, `height`, and `data` properties with the same format as `ImageData`
    at r.addImage (map.js:1294)
    at r.<anonymous> (addimage.html:27)
    at r.St.fire (evented.js:115)
    at r._render (map.js:1980)
    at map.js:2051
```

The fact that `'./cat-icon.png'` is a string seems to conflict with the types listed for the method's `image` parameter.

**Comment by asheemmamoowala** [comment]
> use a local image instead of one from an external URL

@adrianababakanian does this mean a URL served over `file://` prototcol or a URl with a relative URL like `./images/my_img.jpg`?

**Comment by adrianababakanian** [comment]
@asheemmamoowala in this case I was referring to a relative URL, as in the example below:

```
// If the style's sprite does not already contain an image with ID 'cat',
// add the image 'cat-icon.png' to the style's sprite with the ID 'cat'.
if (!map.hasImage('cat')) map.addImage('cat', './cat-icon.png');
```

**Comment by adrianababakanian** [comment]
Confirmed that this example needs to be updated, since `addImage` does not support relative URLs.
