### ISSUE TITLE
Fullscreen button does not appear in mobile safari

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#145]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/fullscreen/](https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/)
* Section: null
* Date received: 2019-11-16T12:09:50.243Z
* Was this page helpful?: 😕

Feedback:
> Missing button to go fullscreen to try it out on iPhone

Confirmed on device.

**Comment by asheemmamoowala** [comment]
This is a known constraint for iPhones. It's documented at https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#Compatible_elements. 

On devices where this control is not supported, a warning message is logged to the console: `This device does not support fullscreen mode.`. But that would be hard to see on an iPhone.

**Comment by danswick** [comment]
Looks like some developers have found [a suitable workaround](https://github.com/mapbox/mapbox-gl-js/issues/7990#issuecomment-737823970). I'm not sure we want to post the workaround in the official docs, but it might be useful to leave a note about mobile safari compatibility.

**Comment by danswick** [comment]
Note added to mapbox-gl-js and will appear in the next release.
