### ISSUE TITLE
Prevent second click for /mapbox-gl-js/example/toggle-layers/

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#16]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/toggle-layers/](https://docs.mapbox.com/mapbox-gl-js/example/toggle-layers/)
* Section: null
* Date received: 2019-08-06T10:33:17.687Z
* Was this page helpful?: 😊

Feedback:
> This prevents having to click a second time in some browsers:
if (visibility === 

We'll need to check this out in a few browsers to see where the issue might be happening.

**Comment by andrewharvey** [comment]
I suspect this is when you click on the button before the map and layer have loaded. A better solution is to have these buttons disabled until the layers have been added to the map.
