### ISSUE TITLE
Describe load event return values for /mapbox-gl-js/api/ (load)

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#17]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/

> Describe the arguments that are passed to the load event -- specifically, the event object.

We should really do a better job of describing return values across the entire GL JS api docs section.

**Comment by colleenmcginnis** [comment]
The load event only returns the target. I don't think we need to document it like we do other event types.
