### ISSUE TITLE
Clarify nature of match, esp compared to `==`

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#174]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/style-spec/](https://docs.mapbox.com/mapbox-gl-js/style-spec/)
* Section: Expressions
* Date received: 2019-12-12T04:41:07.072Z
* Was this page helpful?: 😕

Feedback:
> match could state the nature of the match. Typical matches are strict equality ===, equality with type coercion ==, or regex. Might need to look at the code to figure it out.

**Comment by domlet** [comment]
Just drivin'by:

Here is the docs section for the `match` expression:

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#match

Here's the code for the expression:

https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/expression/definitions/match.js

**Comment by domlet** [comment]
> It looks like it uses an object to pick the match 
> `output = outputs[key]`
> https://github.com/mapbox/mapbox-gl-js/blob/5db846990041e3f3b7c09afc923058fd7eddee01/src/style-spec/expression/definitions/match.js#L104
> 
> I think this means that a and b are equal if 
> `a.toString()` === `b.toString()`
> 
> But I think a and b are already guaranteed to be the same type which means this behavior might be the same as `===`.
> 
> It looks like -native also compares the values as strings. It should be safe to document that.

^ [From Slack](https://mapbox.slack.com/archives/C0S9M8WUS/p1616013990012200?thread_ts=1616009723.012100&cid=C0S9M8WUS)
