### ISSUE TITLE
Add example for setFeatureState

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#18]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/]
* Section: [setFeatureState](https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate)

![Screen Shot 2019-08-12 at 10 20 30 AM](https://user-images.githubusercontent.com/8186438/62884367-35f38900-bceb-11e9-90cd-3c6d2c0b3406.png)

Feature state is a fairly abstract concept; could be useful for us to link to the new [feature state tutorial](https://docs.mapbox.com/help/tutorials/create-interactive-hover-effects-with-mapbox-gl-js/) or the [feature state example](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/) to demonstrate.

**Comment by andrewharvey** [comment]
It seems to be a common theme that people are landing on the API docs but finding it hard to understand without an example. So :+1: for linking to specific examples from more places within the API documentation.

**Comment by katydecorah** [comment]
Merging from #76 

> Does not explain this. how does this work? example?
