### ISSUE TITLE
yarn install fails on node 12 due to sharp install failure

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js-docs#232]
yarn install fails for me on node 12.16.1 due to sharp binaries not found and failing to build from source, currently blocked by https://github.com/mapbox/appropriate-images/pull/23 and then a new release of appropriate-images after which we can update the dependency here

**Comment by katydecorah** [comment]
@andrewharvey this site is set to use Node 10. Want to give the instructions at https://github.com/mapbox/mapbox-gl-js-docs#requirements a try and let us know how it goes?

**Comment by andrewharvey** [comment]
Good point. It would be nice if eventually we can support node 12 too since it will move into [maintenance in March](https://nodejs.org/en/about/releases/) and makes it easier for contributors if they don't need to fiddle with their node version.

**Comment by katydecorah** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js-docs/pull/383
