### ISSUE TITLE
Find more efficient workaround for Batfish to build mapbox-gl-js submodule

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js-docs#257]
With the recent Mapbox GL JS@1.9.0 version bump, this repo started to see build failures on Batfish related to dependencies of Mapbox GL JS:

> 2020-03-23 19:54:57 UTC]Error message: Module not found: Error: Can't resolve '@mapbox/point-geometry' in '/work/mapbox-gl-js-docs/mapbox-gl-js/src/util'

Once I installed the package @mapbox/point-geometry, Batfish then also wanted `@mapbox/unitbezier`. I installed these packages and then pushed a testing branch to staging, but now it wants sinon:

> [2020-03-24 00:47:47 UTC][00:47:46 Batfish]Processing files for static HTML ...
> [2020-03-24 00:47:57 UTC][00:47:55 Batfish]Error: Webpack fatal error. Please check any Batfish configuration options that pass directly into Webpack configuration (webpackLoaders,  webpackPlugins, webpackStaticIgnore).
> [2020-03-24 00:47:57 UTC]
> [2020-03-24 00:47:57 UTC]Error message: Module not found: Error: Can't resolve 'sinon' in '/work/mapbox-gl-js-docs/mapbox-gl-js/src/util'

It seems like something changed in mapbox-gl-js and our build system isn't prepared for it.

I'll continue debugging tomorrow.

cc @danswick

**Comment by katydecorah** [comment]
The new `within` style spec def calls `src/util/util` (via mercator_coordinate -> lng_lat -> util) which helps explain why this error is popping up now. Now, we need to figure out how to handle `mapbox-gl-js/src/util/util.js` to work with Batfish.

**Comment by katydecorah** [comment]
We pushed a fix in #258 but we would like to return to debugging this more when we have more time as it's not ideal to have to install the mapbox-gl-js submodule dependencies during build.

**Comment by katydecorah** [comment]
Carrying over a couple comments @danswick left on #258 which I think are important to note:

> I believe the gist is: the style spec depends on a module from mapbox-gl-js and that module depends on an external package. We've built in a step to install the style spec's dependencies, but did not have one for mapbox-gl-js's dependencies, so the module in question does not have access to the necessary dependency.

> After doing some verbose logging, I think I tracked it down to this import statement: https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/expression/definitions/within.js#L10, which was added to support the within expression. It's pretty wild that this hasn't come up before, but here we are. The style spec monorepo design is probably impossible to disentangle and I guess we'll have to live with it!

**Comment by stevage** [comment]
I take it this is way we can't see the style-spec documentation for the new `within` operator yet?

**Comment by katydecorah** [comment]
> I take it this is way we can't see the style-spec documentation for the new within operator yet?

@stevage The site is fixed, but we're keeping this open to remind us to find a more efficient fix. I'll rename the ticket so it's less confusing. As far as `within` documentation, new definitions need extra metadata to be displayed on the site and that work is happening in #262  (ref #259 - scheming on a test to help remind us to document all definitions)

**Comment by katydecorah** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-js-docs/pull/323
