### ISSUE TITLE
Update TOC for release-danube

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js-docs#276]
GL-JS `release-danube` introduces a few new methods and classes in the `mapboxgl`namespace. These need to be updated in the `documentation.yml` file when upgrading the docs to the new release.

cc @karimnaaji @ansis @arindam1993

**Comment by karimnaaji** [comment]
Thanks for the reminder, updated in the pending docs update PR https://github.com/mapbox/mapbox-gl-js-docs/commit/140583ba94710c800badc5bd44f9db75c2021217.
