### ISSUE TITLE
transformRequest example uses a method not supported in IE

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js-docs#280]
The `transformRequest` demo in the docs uses the `String.prototype.startsWith` method which [is not supported in IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Browser_compatibility). I'm not sure if we have a policy on using methods that aren't supported by all browsers in examples, but this could cause problems if someone tried to implement it in IE. 

<img width="552" alt="Screen Shot 2020-04-21 at 3 27 33 PM" src="https://user-images.githubusercontent.com/4523080/79920735-9f34ab80-83e5-11ea-9702-54d5568c20df.png">

**Comment by katydecorah** [comment]
@ryanhamley the docs subdomain browser support includes IE 11. 

* Is this code for an inline API code example? If so, we may want to add a comment with a note about browser support.
* Is this code for an example page? If so, then we'll need to add any appropriate polyfills to make sure the example loads properly in IE11.

**Comment by ryanhamley** [comment]
@katydecorah This is in the API reference docs example for map options. There's no direct link to it but it's below the map options and just above where "Instance members" starts (i.e. right above https://docs.mapbox.com/mapbox-gl-js/api/#map#scrollzoom).

**Comment by andrewharvey** [comment]
This has been changed in https://github.com/mapbox/mapbox-gl-js/pull/9607/commits/c5923cd74ac1e08b01bbf134985f4dd6600982ce

Personally I favour `startsWith` because it's so much more readable, however given the comment says begins with, I think it's fine to change this to support IE11.

**Comment by katydecorah** [comment]
docs.mapbox.com and Mapbox GL JS v2 no longer supports Internet Explorer, so this issue is no longer an issue. Closing here!
