### ISSUE TITLE
Octothorpes (#) are being removed from JSDoc nested link tags

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#287]
While reviewing https://github.com/mapbox/mapbox-gl-js/pull/9607, I noticed that link tags like `{@link Map#fitBounds}` are ending up as `docs.mapbox.com/mapbox-gl-js/api/#mapfitbounds`. I _think_ this is happening somewhere in the docs page's components, but am not sure where yet. 

It looks like this has always been the case since it's the same situation in the currently-published site.

cc @katydecorah

**Comment by asheemmamoowala** [comment]
I started some work on this over at https://github.com/mapbox/mapbox-gl-js-docs/pull/191, but have not had a chance to look into it again. The sluggers are used inconsistently and I noticed that links to events are also broken right now.

**Comment by andrewharvey** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/4568 and #121

**Comment by danswick** [comment]
@andrewharvey wow! this is an old issue 😂. 

Thanks for that, @asheemmamoowala! Events have been working for me, so I'll look into this a bit more to see where the inconsistency is coming from.
