### ISSUE TITLE
Add 3d model with BabylonJS

### ISSUE THREAD

**Issue by fabsharp** [mapbox/mapbox-gl-js-docs#378]
I used [babylonjs](https://babylonjs.com) to render 3d model in mapbox : https://jsfiddle.net/fabsharp/sk6puxhq/.

Are you interested to add this example to your documentation ? I can make a PR if you want

**Comment by asheemmamoowala** [comment]
We haven't had a lot of requests for this, but there is one open (https://github.com/mapbox/mapbox-gl-js-docs/issues/92) with a `help wanted` tag.

Thank you for offering, and in advance for contributing to the docs! I'll close this and you can link your PR to #92 when it's ready.
