### ISSUE TITLE
Top-level ordering in style spec

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js-docs#380]
![Screen Shot 2020-08-03 at 12 37 06 pm](https://user-images.githubusercontent.com/678344/89140804-169ddd80-d586-11ea-940f-b0e86150ea55.png)

The ordering of items in the side panel seems suboptimal. Is there any particular reason it's this way?

In particular:

- sources and layers should be next to each other.
- light doesn't seem important enough to warrant such a high place

I would suggest:

- introduction
- root
- sources
- layers
- sprite
- glyphs (keeping sprite and glyphs next to each other, since they are similar in purpose)
- transition
- light
- expressions
- types (keeping next to expressions, because they are closely related, although types seem less important)
- other

**Comment by domlet** [comment]
Thank you @stevage for the helpful suggestion!

**Comment by stevage** [comment]
I'm glad you didn't follow my suggestion about putting the expressions near the bottom. Where you put them is much better. :)
