### ISSUE TITLE
Example of geocoder control placed outside the map...isn't.

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js-docs#39]
The geocoder control is, um, not outside the map.

<img width="541" alt="screenshot 2019-02-05 17 15 54" src="https://user-images.githubusercontent.com/678344/52256169-cf6f6600-2969-11e9-985e-22c8fc6592cf.png">

I'm not sure exactly what's going wrong here. I suspect maybe because the map is taking up 100% of the container it's within, there's just nowhere for the control to be that isn't in top of the map.

The simplest fix is to change the styling of `#map` to be `top: 100px;` instead of `top: 0;`

**Comment by katydecorah** [comment]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/)
* Section: null
* Date received: 2019-09-26T19:18:57.506Z
* Was this page helpful?: 😕

Feedback:
> Either I misunderstood or the heading is not right. How is this outside the map?

**Comment by andrewharvey** [comment]
> Honestly, it doesn't make much sense to me to give an example that doesn't achieve anything that anyone would want: who wants a control that is "outside" the map, but still on top of it? :)

Well it's here to help show how to get the control outside the map element, which then lets you place it wherever else you want on the page. The CSS or placement on the DOM is your choice then.

So while I still believe this example does it's job as is, given multiple user reports of confusion here I've proposed https://github.com/mapbox/mapbox-gl-js-docs/pull/234 to make the search control appear outside of the map graphically.
