### ISSUE TITLE
Create a time slider example not functioning as expected

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/mapbox-gl-js-docs#393]
The https://docs.mapbox.com/mapbox-gl-js/example/timeline-animation/ works on the examples page, but when the example is copied and pasted into a text editor and run, no points show and the slider doesn't show the filtered month values. 

I've attached a working example below: 
[mapTest.html.zip](https://github.com/mapbox/mapbox-gl-js-docs/files/5091267/mapTest.html.zip)

**Comment by seanhellier** [comment]
Hi ZiZi, thanks for sending me the link.

Have you guys figured out what's going on with this issue?
