### ISSUE TITLE
Feedback for /mapbox-gl-js/api/ (Evented)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#49]
Category of feedback: _more details needed_

*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/](https://docs.mapbox.com/mapbox-gl-js/api/#evented)
* Section: [evented](https://docs.mapbox.com/mapbox-gl-js/api/#evented)

> Where is the list of events???

**Comment by katydecorah** [comment]
Closing in favor of #9
