### ISSUE TITLE
Add example for MapDataEvent

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#50]
Category of feedback: _needs usage details/short example_

*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/](https://docs.mapbox.com/mapbox-gl-js/api/#mapdataevent)
* Section: (MapDataEvent)[https://docs.mapbox.com/mapbox-gl-js/api/#mapdataevent]

> Supply an example of the usage, pretty please.

**Comment by katydecorah** [comment]
Merging feedback from #110

> No examples...

**Comment by katydecorah** [comment]
Closing in favor of planning ticket: https://github.com/mapbox/mapbox-gl-js-docs/issues/236
