### ISSUE TITLE
"Check if Mapbox GL JS is supported" example not working in IE 11.0

### ISSUE THREAD

**Issue by domlet** [mapbox/mapbox-gl-js-docs#545]
I tried opening this page:

* https://docs.mapbox.com/mapbox-gl-js/example/check-for-support/

In this browser emulator:

* https://live.browserstack.com/dashboard?utm_source=chrome&utm_medium=extension&utm_campaign=quick-launch#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2F192.168.7.223%3A9967%2FVideo&speed=1

```
os=Windows
os_version=10
browser=IE
browser_version=11.0
```

The result is that the map does not load, so I expected to see the `Your browser does not support Mapbox GL` alert.

However, I did not see the alert anywhere.

Am I doing something wrong, or is this example not working properly?

Screenshot:

![Screen Shot 2021-04-22 at 3 49 56 PM](https://user-images.githubusercontent.com/6026447/115794657-176fdd00-a36a-11eb-8992-7e027b30ee40.jpg)

/cc: @mapbox/gl-js

**Comment by katydecorah** [comment]
@domlet docs.mapbox.com no longer supports IE 11. The page is failing before Mapbox GL JS in the example can run, this is expected and accepted.

**Comment by domlet** [comment]
Got it, thanks Katy!
