### ISSUE TITLE
Refere back to the addControl section under ScaleControl

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/mapbox-gl-js-docs#55]
We received feedback through the feedback widget on the [`ScaleControl`](https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol) documentation. It was not clear to them that they should refer to the [`addControl`](https://docs.mapbox.com/mapbox-gl-js/api/#map#addcontrol) section to position the scale control on the map. We could be more direct and refer back to the `addControl` section.

**Comment by katydecorah** [comment]
More feedback:

> Would be nice to know if you could style it or not and if so, how
