### ISSUE TITLE
Does zoomend fire after tiles are loaded/rendered?

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#62]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/]

Does the firing of this event include the time it takes to redraw any polygons at the new location?

**Comment by domlet** [comment]
I ran a quick test:

* https://jsfiddle.net/domlet/2ujLqc6b/13/

...and I can see a console message for `zoomend` before some labels appear on the map

...so I'm going to run with this and tag GL JS on a PR.
