### ISSUE TITLE
Feedback for /mapbox-gl-js/example/data-driven-circle-colors/

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/mapbox-gl-js-docs#66]
A user submitted feedback through the widget on the bottom of the page on [/mapbox-gl-js/example/data-driven-circle-colors/](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/):

> What does the data look like? I have no idea how to add a custom data set to a map and this examples obscures the entire data set. It looks nice on a map but I have no idea how to apply it myself.

We should consider adding a code comment that explains the data properties relevant to the expression used in this example.

**Comment by andrewharvey** [comment]
Or even when adding the Mapbox Tileset source, we include a comment showing a single GeoJSON feature from that tileset, so people can see the format of the data in the tileset, which is exactly issue #43. PR for that at #67

**Comment by colleenmcginnis** [comment]
Fixed in #67  🎉 Thanks @andrewharvey!

**Comment by domlet** [comment]
1. I searched in Studio to see if I could examine the tileset myself, and it is not available for inspection:

![image](https://user-images.githubusercontent.com/6026447/89233482-8324d680-d59e-11ea-958d-4f8fdc852e30.png)

2. A [StackOverflow user](https://stackoverflow.com/questions/53940409/what-is-the-source-and-its-format-for-the-data-points-plotted-on-this-map-from) is wondering something similar:

>  There is a url "mapbox://examples.8fgz4egr" present in the 'source' 
> but what kind of data is it ? 
> is it json or what ? 
> How do I change the source and put my own?

![image](https://user-images.githubusercontent.com/6026447/89233417-68eaf880-d59e-11ea-8190-bd4f91f680d0.png)

**Comment by HeyStenson** [comment]
I feel like the question behind the feedback we've gotten on this is actually _"where can I access this tileset for my own use?"_ I think that a good way to address this could be to call out where the original data came from with a link in the code comments. But this info has been a lot harder to track down than I anticipated - I thought it'd be available via http://www.bayareacensus.ca.gov/index.html, but no such luck. This is a long shot since the tileset was created in 2016, but does anyone from @mapbox/docs or @mapbox/gl-js know where the data used to create the tileset came from?

**Comment by asheemmamoowala** [comment]
> question behind the feedback we've gotten on this is actually "where can I access this tileset for my own use?"

Here are two other ways to help make this example easier to replicate for customer data sets:
- Switch to a new tileset with a publicly available MTS recipe and documented data source
- Easier - use a static GeoJSON data source hosted in this project.

**Comment by colleenmcginnis** [comment]
>This is a long shot since the tileset was created in 2016, but does anyone from @mapbox/docs or @mapbox/gl-js know where the data used to create the tileset came from?

I don't think we should prioritize providing this data for use in their application because we don't maintain the data, and the fact that it's from 2016 and not on the bay area census site underscores this point.

Instead, I think we should just make it clear in a code comment and/or note in the Markdown file that this URL points to a Mapbox-hosted tileset that was created by uploading geospatial data (CSV, GeoJSON, etc) via the [Mapbox Studio Tilesets](https://studio.mapbox.com/tilesets/) page (or switch to an MTS tileset as Asheem suggested though maybe that should be a separate effort for all examples using vector sources).

What do you think about this approach @HeyStenson @asheemmamoowala?

**Comment by colleenmcginnis** [comment]
@HeyStenson jfyi I included this in https://github.com/mapbox/mapbox-gl-js-docs/pull/535. Let me know what you think!
