### ISSUE TITLE
Feedback for /mapbox-gl-js/api/#evented (on)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#74]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: https://docs.mapbox.com/mapbox-gl-js/api/#evented
* Section: https://docs.mapbox.com/mapbox-gl-js/api/#evented#on

> IMHO, it misses the different types of 'type' that are handled, or at least a link to thoses

**Comment by HeyStenson** [comment]
Further feedback on this section:

> witch types are valid?

**Comment by katydecorah** [comment]
Further feedback on this section:


> I have no idea what events there are or where to look. What events? Is there a list of mapbox gl events?

**Comment by katydecorah** [comment]
> Please enumerate available event types.

**Comment by katydecorah** [comment]
Closing in favor of #9
