### ISSUE TITLE
Feedback for /mapbox-gl-js/api/#evented (type)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#75]
This feedback was submitted by a user through the feedback widget on the bottom of the page.

Page: https://docs.mapbox.com/mapbox-gl-js/api/#evented
Section: https://docs.mapbox.com/mapbox-gl-js/api/#evented#type

> Give a list of possible values

**Comment by katydecorah** [comment]
Additional feedback:

> I don't know [what] are the [redacted] types!!!

**Comment by katydecorah** [comment]
Closing in favor of #9
