### ISSUE TITLE
Feedback for /mapbox-gl-js/api/#map#setfeaturestate

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#76]
This feedback was submitted by a user through the feedback widget on the bottom of the page.

Page: https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate

> Does not explain this. how does this work? example?

**Comment by andrewharvey** [comment]
I reckon just linking to https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/ would suffice.

**Comment by katydecorah** [comment]
closing in favor of https://github.com/mapbox/mapbox-gl-js-docs/issues/18
