### ISSUE TITLE
Feedback for /mapbox-gl-js/example/navigation/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#77]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/navigation/](https://docs.mapbox.com/mapbox-gl-js/example/navigation/)
* Section: null
* Date received: 2019-09-13T16:44:27.317Z
* Was this page helpful?: 😕

Feedback:
> does not work

This example _does_ work, but I think this is a case where more explanation in the description would better set reader expectations about what the example is demonstrating.

**Comment by andrewharvey** [comment]
Maybe just adding an extra note that by default the control is added to the top right corner of the map... :thought_balloon:

**Comment by katydecorah** [comment]
Closing here since it's not clear what doesn't work for the user
