### ISSUE TITLE
Feedback on /mapbox-gl-js/style-spec/#sprite

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#78]
This feedback was submitted by a user through the feedback widget on the bottom of the page.

Page: https://docs.mapbox.com/mapbox-gl-js/style-spec/
Section: https://docs.mapbox.com/mapbox-gl-js/style-spec/#sprite

> An example to use the sprites might have made it more clear

**Comment by danswick** [comment]
I wonder if this feedback was made before the current iteration of the sprite section? IMO, this section does a good job of explaining _how to use a sprite_, but this user probably is confused about the connection between `sprite` and `icon-image` in a symbol layer. I think the connection is explained pretty well here. We could always go into more detail, but I'm not sure that the sprite section itself is the right place to do that. The `icon-image` section of the style spec could probably use an example, though!

Let's close this for now in favor of the style spec example tracking issue https://github.com/mapbox/documentation/issues/660
