### ISSUE TITLE
Request for geocoder example with no marker added to map

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#79]
A user left feedback on https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/ and https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ with the request that we create an example for `mapbox-gl-geocoder` that does not add a marker to the map:

> Seriously, you should have an example of geocoder without the marker. Is it even possible to hide it?

> Need an example without the marker - for cases when user should add his/her own marker.

We could create a new example with the geocoder that has `options.marker` set to false to demo this: https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters

**Comment by andrewharvey** [comment]
I would have thought this would be pretty obvious from the geocoder API docs... but an example should be fine.

**Comment by HeyStenson** [comment]
Closing this - agree with @andrewharvey that an example isn't really necessary.
