### ISSUE TITLE
Add example for PointLike

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#84]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/#pointlike](https://docs.mapbox.com/mapbox-gl-js/api/#pointlike)

> No example

**Comment by katydecorah** [comment]
Closing in favor of planning ticket: https://github.com/mapbox/mapbox-gl-js-docs/issues/236
