### ISSUE TITLE
Add example for zoomIn

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#87]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: https://docs.mapbox.com/mapbox-gl-js/api/#map
* Section: zoomIn
* Date received: 2019-09-18T16:29:44.020Z
* Was this page helpful?: 😕

Feedback:
> Missing example

A link to an example that uses `zoomIn` or a small code snippet demonstrating its use could be beneficial here.

**Comment by katydecorah** [comment]
Closing in favor of planning ticket: https://github.com/mapbox/mapbox-gl-js-docs/issues/236
