### ISSUE TITLE
Add possible event types

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js-docs#9]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/api/](https://docs.mapbox.com/mapbox-gl-js/api/)

---

Note: This issue compiles multiple customer feedback. While pertaining to different methods, all customers are requesting similar information: the values for `type`.

---

> Where do I find the valid values that can be passed as the `type` parameter? `string` is a bit broad.
https://docs.mapbox.com/mapbox-gl-js/api/#evented#on

> What are the possible event types?
https://docs.mapbox.com/mapbox-gl-js/api/#evented#on

> what are the possible types?
https://docs.mapbox.com/mapbox-gl-js/api/#map#on

> list available types?
https://docs.mapbox.com/mapbox-gl-js/api/#mapmouseevent

**Comment by danswick** [comment]
We got another related request:

> What are the possible values for 'type', i.e. 'moveend'?

**Comment by katydecorah** [comment]
> Tell about all the types

https://docs.mapbox.com/mapbox-gl-js/api/#mapmouseevent#type

**Comment by katydecorah** [comment]
Merging from #107 

> A list or link to the event types would be nice :-)

> I would love to get a link here to which events are supported.

> What are the types?

**Comment by katydecorah** [comment]
Merging from #75 

https://docs.mapbox.com/mapbox-gl-js/api/#evented#type
> Give a list of possible values

> I don't know [what] are the [redacted] types!!!

**Comment by katydecorah** [comment]
Merging from #74 

https://docs.mapbox.com/mapbox-gl-js/api/#evented#on

> IMHO, it misses the different types of 'type' that are handled, or at least a link to thoses

> witch types are valid?

> I have no idea what events there are or where to look. What events? Is there a list of mapbox gl events?

> Please enumerate available event types.

**Comment by katydecorah** [comment]
Merged from #49

> Where is the list of events???
