### ISSUE TITLE
Define a layer change for triggerRepaint

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js-docs#93]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: https://docs.mapbox.com/mapbox-gl-js/api/#map#triggerrepaint

> What defines a "layer change"?

**Comment by danswick** [comment]
closing in favor of https://github.com/mapbox/documentation/issues/660

**Comment by danswick** [comment]
Whoops, commented on/closed the wrong issue! 🙈
